name: Deploy Angular SPA to GitHub Pages

on:
  push: 
    branches:   
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Build
      run: |
         npm install -g @angular/cli
         npm install
         ng build --base-href="/office-buddy/"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: dist
        enable_jekyll: true
